const stringsId = {
    txtSilaomHospitals: "Siloam Hospitals",
    //login
    txtLogin: "Log In",
    txtLoginDescription: "Please login using your User Name",
    txtUserName: "User Name",
    txtUserNamePlaceholder: "User Name",
    txtPassword: "Password",
    txtPasswordPlaceholder: "Password",
    txtSuperAdmin: "Super Admin",
    txtLogout: "Logout",

    //tab menus
    txtMenuDashboard: "DASHBOARD (ANALYTICS)",
    txtMenuComeptition: "COMPETITION",
    txtMenuChallenge: "CHALLENGE",
    txtMenuLeaderboard: "LEADERBOARD",
    txtMenuReward: "REWARDS",
    txtMenuDepartment: "DEPARTMENT",
    txtMenuJobTitle: "JOB TITLE",
    txtMenuUserManagement: "USER MANAGEMENT",
    txtMenuPointHistory: "POINT HISTORY",
    txtMenuRewardHistory: "REWARDS HISTORY",
    txtMenuPackageInvoice: "PACKAGE & INVOICE",
    txtMenuBanner: "BANNER",
    txtMenuBroadcast: "BROADCAST",
    txtMenuThemeSetting: "THEME SETTING",
    txtMenuReport: "REPORT",
    txtMenuPayor: "PAYOR",
    txtMenuPayorList: "PAYOR LIST",
    txtMenuMasterData: "MASTER DATA",

    txtMenuMyWellness: "MY WELLNESS",
    txtMenuPackage: "PACKAGE",
    txtMenuHealthRiskQuiz: "HEALTH RISK QUIZ",
    txtMenuChallengeTemplate: "CHALLENGE TEMPLATE",
    txtMenuRewardType: "REWARD TYPE",
    txtDashboard: "Dashboard",
    txtUserManagement: "User Management",
    txtJobLevel: "Job Title",
    txtChallenge: "Challenge",
    txtCompetition: "Competition",
    txtLeaderboard: "Leaderboard",
    txtRedeem: "Redeem",
    txtRewards: "Rewards",
    txtRewardHistory: "Rewards History",
    txtPointHistory: "Point History",
    txtAnalytics: "Analytics",
    txtPackageAndInvoice: "Package & Invoice",
    txtBanner: "Banner",
    txtThemeSetting: "Theme Setting",
    txtBroadcast: "Broadcast",
    txtReport: "Report",
    txtSiloamAdmin: "Siloam Admin",
    txtPayor: "Payor",
    txtPayorList: "Payor List",
    txtBanner: "Banner",
    txtMasterData: "Master Data",
    txtMyWellness: "My Wellness",
    txtPackage: "Package",
    txtHealthRiskQuiz: "Health Risk Quiz",
    txtChallengeTemplate: "Challenge Template",
    txtRewardType: "Reward Type",
    txtPackageInvoiceSearchPlaceholder: "by ID, Package",

    superAdminRole: 'superadmin',
    payorAdminRole: 'payoradmin',

    //user management
    txtImportCSV: "IMPORT .XLSX",
    txtAddNewUser: "ADD NEW USER",

    txtImportLabel: "Choose a .XLSX File From Your Computer",
    txtImportButton: "Import",
    txtChooseFile: "Browse File",

    txtFilterByJobLevel: "Filter by Job Title",
    txtSearch: "Search",
    txtUserManagementSearchPlaceholder: "by id, user name, phone number",
    txtApply: "APPLY",
    txtClear: "CLEAR",

    txtCreateNewUser: "Create New User",
    txtProfilePicture: "Profile Picture",
    txtImageSizeDesc: ".jpeg ; 480 x 480",
    txtBtnBrowse: "BROWSE",
    txtBtnSave: "SAVE",
    txtBtnNext: "NEXT",
    txtSetupNotifications: "SETUP NOTIFICATIONS",
    txtBtnDelete: "DELETE",
    txtBtnCancel: "CANCEL",

    txtFieldEmployeeID: "Employee ID",
    txtFieldPayorName: "Payor Name",
    txtFieldMCUPayor: "MCU Payor",
    txtFieldUserName: "User Name",
    txtFieldName: "Name",
    txtFieldJobLevel: "Job Title",
    txtFieldDepartment: "Department",
    txtFieldDateOfBirth: "Date of Birth",
    txtFieldDateOfBirthInfo: " ex: 1987-10-31",
    txtFieldPhoneNumber: "Phone Number",
    txtFieldJobName: "Job Title",
    txtFieldEMail: "E-mail",
    txtFieldPackage: "Package",
    txtEmployeeDetail: "Employee Detail",

    txtUserInfo: "User Info",
    txtProfile: "Profile",
    txtHealthQuiz: "Health Quiz",
    txtAll: "All",

    //error page
    txtBtnBackToDashboard: "BACK TO DASHBOARD",
    //payor management

    txtPayorDetail: "Payor Detail",
    txtPayorList: "Payor List",
    txtBtnAddNewPayor: "ADD NEW PAYOR",
    txtAddNewPayor: "Add New Payor",
    txtActive: "Active",
    txtNonActive: "Non-Active",

    txtFilterByStatus: "Filter by Status",
    txtPayorSearchPlaceholder: "by ID, name, phone number",

    txtFieldPayorID: "Payor ID",
    txtFieldPayorName: "Payor Name",
    txtFieldStatus: "Status",
    txtFieldAddress: "Address",
    txtFieldAdminUsername: "Admin Username",
    txtFieldLogo: "Logo",

    txtPayorAdmin: "Payor Admin",

    txtOldPassword: "Old Password",
    txtNewPassword: "New Password",
    txtNewPasswordConfrim: "New Password Confirm",
    txtChangePassword: "Change Password",

    //banner management

    txtFilterByPayor: "Filter By Payor",
    txtBanner: "Banner",
    txtFieldBannerID: "Banner ID",
    txtFieldBannerTitle: "Banner Title",
    txtFieldTitle: "Title",
    txtFieldTitleInd: "Indonesian Title",
    txtFieldDescriptionInd: "Description in Bahasa Indonesia",
    txtFieldPayorName: "Payor Name",
    txtFieldPostedDate: "Posted Date",
    txtBtnAddNewBanner: "ADD NEW BANNER",
    txtAddNewBanner: "Add New Banner",
    txtBannerDetail: "Banner Detail",
    txtBannerImage: "Banner Image",
    txtBannerPlaceholder: "by ID, Title",

    //my wellness record
    txtSymptomRecord: "Symptoms",
    txtFieldRecordID: "Record ID",
    txtFieldDate: "Date",
    txtFieldWeight: "Weight (kg)",
    txtFieldUnit: "Unit",
    txtWeightRecord: "Weight",
    txtWeightRecordDetail: "Weight Detail",
    txtWeightRecordSearchPlaceholder: "by ID",
    txtBodyHeight: "Body Height (cm)",
    txtBodyWeightTarget: "Body Weight Target (kg)",
    txtStatusArchieved: "ARCHIEVED",
    txtStatusNonArchieved: "NOT ARCHIEVED",
    txtFieldValue: "Value",



    txtPrescription: "Prescription",
    txtPrescriptionDetail: "Prescription Detail",
    txtPrescriptionSearchPlaceholder: "by ID, Prescription Name",
    txtFieldPrescriptionID: "Prescription ID",
    txtFieldDosage: "Dosage",
    txtFieldAssignBy: "Assign By",
    txtFieldFrequence: "Frequence",
    txtFieldDailyFrequency: "Times in a day",
    txtFieldServings: "Servings",
    txtFieldAssignedDate: "Assigned Date",
    txtFieldEndDate: "End Date",
    txtFieldBMI: "BMI",
    txtSectionMedicationTime: "MEDICATION TIME",
    txtFieldMedicationTime: "Medication Time",

    txtFieldTotalCalories: "Total Calories (cal)",
    txtDailyCaloriesTarget: "Daily Calories Target (cal)",

    txtDietRecord: "Food",
    txtDietRecordDetail: "Food Detail",
    txtDietRecordSearchPlaceholder: "by ID",

    txtExerciseRecord: "Exercise",
    txtExerciseRecordDetail: "Exercise Detail",
    txtExerciseRecordSearchPlaceholder: "by ID",

    txtBloodGlucoseRecord: "Blood Glucose",
    txtBloodGlucoseRecordDetail: "Blood Glucose Detail",
    txtBloodGlucoseRecordSearchPlaceholder: "by ID",

    txtStep: "Step",
    txtStepDetail: "Step Detail",
    txtStepTarget: "Step Target",
    txtFieldStep: "Step",
    txtStepSearchPlaceholder: "by ID",

    txtSleep: "Sleep",
    txtSleepDetail: "Sleep Detail",
    txtSleepTarget: "Sleep Target",
    txtSleepSearchPlaceHolder: "by ID",
    txtFieldSleepDuration: "Sleep Duration",
    txtTarget: "Target",


    txtStair: "Stair",
    txtStairDetail: "Stair Detail",
    txtStairTarget: "Stair Target",
    txtStairSearchPlaceHolder: "by ID",

    txtFieldStair: "Stair (floor)",
    txtFieldStairTarget: "Target (floor)",
    //my wellness

    txtHealthRisk: "Health Risk",
    txtConditionList: "Condition List",
    txtSymptomList: "Symptom List",
    txtMedicineList: "Medicine List",
    txtFoodList: "Food List",
    txtExerciseList: "Exercise List",
    txtFieldHealthRiskID: "Health Risk ID",
    txtFieldHealthRiskName: "Health Risk Name",
    txtFieldHealthRiskShortDescription: "Health Risk Short Description",
    txtFieldHealthRiskDescription: "Health Risk Description",
    txtFieldHealthRiskNameInd: "Health Risk Name(Ind)",
    txtFieldHealthRiskShortDescriptionInd: "Health Risk Short Description(Ind)",
    txtFieldHealthRiskDescriptionInd: "Health Risk Description(Ind)",
    txtFieldSort: "Sort",
    txtFieldCoditionID: "Condition ID",
    txtFieldConditionName: "Condition Name",
    txtFieldSymptomID: "Symptom ID",
    txtFieldSymptomName: "Symptom Name",
    txtFieldMedicineID: "Medicine ID",
    txtFieldMedicineName: "Medicine / Vitamin Name",
    txtFieldMedicine: "Medicine",
    txtFieldMealID: "Meal ID",
    txtFieldMealName: "Meal Name",
    txtFieldCalories: "Calories (cal)",
    txtFieldServingSize: "Serving Size",
    txtFieldCarb: "Carb",
    txtFieldGram: "Gram",
    txtFieldProtein: "Protein",
    txtFieldFat: "Fat",
    txtFieldExerciseID: "Exercise ID",
    txtFieldExerciseName: "Exercise Name",
    txtFieldCalroiesPerMinute: "Calories Burned per Minute (cal)",
    txtFieldTargetCalories: "Target (cal)",
    txtFieldCalories: "Calories (cal)",
    txtFieldDuration: "Duration",

    txtSectionHealthRiskDescription: "HEALTH RISK DESCRIPTION",
    txtStatusLow: "Status Low",
    txtStatusMedium: "Status Medium",
    txtStatusHigh: "Status High",

    txtWater: "Water",
    txtWaterDetail: "Water Detail",
    txtFieldWater: "Water (glass)",
    txtFieldWaterTarget: "Target (glass)",
    txtWaterSearchPlaceholder: "by ID",

    txtVeggie: "Veggies",
    txtVeggieDetail: "Veggies Detail",
    txtFieldVeggie: "Portion",
    txtFieldVeggieTarget: "Target",
    txtVeggieSearchPlaceholder: "by ID",

    txtFruit: "Fruits",
    txtFruitDetail: "Fruits Detail",
    txtFieldFruit: "Portion",
    txtFieldFruitTarget: "Target",
    txtFruitSearchPlaceholder: "by ID",

    txtSymptomDetail: "Symptom Detail",
    txtAddNewSymptom: "Add New Symptom",
    txtBtnAddNewSymptom: "ADD NEW SYMPTOM",
    txtSymptomSearchPlaceholder: "by ID, Symptom Name",

    txtMealDetail: "Food Detail",
    txtAddNewMeal: "Add New Food",
    txtBtnAddNewMeal: "ADD NEW FOOD",
    txtMealSearchPlaceholder: "by ID, Food Name",

    txtExerciseDetail: "Exercise Detail",
    txtAddNewExercise: "Add New Exercise",
    txtBtnAddNewExercise: "ADD NEW EXERCISE",
    txtExerciseSearchPlaceholder: "by ID, Exercise Name",

    txtHealthRiskDetail: "Health Risk Detail",
    txtAddNewHealthRisk: "Add New Health Risk",
    txtBtnAddNewHealthRisk: "ADD NEW HEALTH RISK",
    txtHealthRiskSearchPlaceholder: "by ID, Health Risk Name",

    txtMedicineDetail: "Medicine Detail",
    txtAddNewMedicine: "Add New Medicine",
    txtBtnAddNewMedicine: "ADD NEW MEDICINE",
    txtMedicineSearchPlaceholder: "by ID, Medicine / Vitamin Name",
    txtIsAntiDiabetic: "Anti Diabetic",
    txtOther: "Other",

    txtMedicationRecordDetail: "Medication Detail",
    txtMedicationRecord: "Medication",
    txtMedicationRecordSearchPlaceholder: "by ID, Medication Name",

    txtFieldNote: "Note",

    txtSectionFrequency: "FREQUENCY",


    txtHealthRiskSearchPlaceholder: "by ID, Health Risk Name",

    //package
    txtAddNewPackage: "Add New Package",
    txtPackageSearchPlaceholder: "by ID, Title",
    txtBtnAddNewPackage: "ADD NEW PACKAGE",
    txtStatusActive: "ACTIVE",
    txtStatusInActive: "INACTIVE",
    txtFieldPackageID: "Package ID",
    txtFieldPackageName: "Package Name",
    txtFieldPackagePeriod: "Period (days)",
    txtFieldPrice: "Price",
    txtFieldPackageFeatures: "PACKAGE FEATURES",
    txtFeatureHealthRisk: "Health Risk",
    txtFeatureConsultation: "Consultation",
    txtFeatureSymptoms: "Symptoms",
    txtFeaturePrescriptions: "Prescriptions",
    txtFeatureMedications: "Medications",
    txtFeatureWeight: "Weight",
    txtFeatureFood: "Food",
    txtFeatureSleep: "Sleep",
    txtFeatureStep: "Step",
    txtFeatureWater: "Water",
    txtFeatureVeggies: "Veggies",
    txtFeatureFruit: "Fruits",
    txtFeatureExercise: "Exercise",
    txtFeatureStair: "Stair",
    txtFeatureBloodGlucose: "Blood Glucose",
    txtFeatureCustomizableChallenge: "Customizable Challenge via Payor Admin",
    txtFeatureCustomizableRewards: "Customisable Rewards via Payor Admin",
    txtPackageDetail: "Package Detail",

    txtSetAdminAccessibility: "Set Admin Accessibility",
    txtSeeAdminAccessibility: "See Admin Accessibility",
    txtBtnSetAdminAccess: "SET ADMIN ACCESS",

    txtFieldAdminPage: "Admin Page",
    txtFieldCreate: "Create",
    txtFieldRead: "Read",
    txtFieldUpdate: "Update",
    txtFieldDelete: "Delete",


    //challenge

    txtChallenge: "Challenge",
    txtChallengeDetail: "Challenge Detail",
    txtBtnChallengeTemplate: "CHALLENGE TEMPLATE",
    txtBtnAddNewChallenge: "ADD NEW CHALLENGE",
    txtFilterByChallengeCategory: "Filter By Challenge Category",
    txtFilterByStatus: "Filter By Status",
    txtSearchChallengePlaceholder: "by ID, Title",
    txtStatusExpired: "EXPIRED",
    txtStatusStarted: "STARTED",
    txtStatusPending: "PENDING",

    txtFieldChallengeID: "Challenge ID",
    txtFieldCategory: "Category",
    txtFieldChallengeCategory: "Challenge Category",
    txtFieldChallengeTitle: "Challenge Title",
    txtFieldPeriod: "Period",
    txtFieldChallengeImage: "Challenge Image",
    txtFieldDescription: "Description",
    txtFieldTotalTarget: "Total Target",
    txtFieldTotalDailyTarget: "Total Daily Target",
    txtFieldReward: "Reward (coins)",
    txtAddNewChallenge: "Add New Challenge",
    txtChallengeSectionTitleSpecify: "Specify the Challenge You Want to Make",
    txtChallengeSectionTitleChoosePeriod: "Choose the Challenge Period Time",
    txtOneTime: "One Time",
    txtRepeat: "Repeat",
    txtRepeatFrequency: "Repeat Frequency",
    txtStartDate: "Start Date",
    txtRepeatFor: "Repeat for (days/weeks)",
    txtRepeatForOnly: "Repeat for",
    txtRepeatForPlaceholder: "Repeat for",
    txtChallengeSectionTitleChooseRange: "Choose Range for Your Challenge Target",
    txtSectionAge: "AGE",
    txtSectionGender: "GENDER",
    txtSectionHealthRisk: "HEALTH RISK",
    txtSectionJobLevel: "JOB LEVEL",
    txtAllAge: "All Age",
    txtSelected: "Selected",
    txtFieldMinimumAge: "Minimum Age",
    txtFieldMaximumAge: "Maximum Age",
    txtAllGender: "All Gender",
    txtFieldGender: "Gender",
    txtEveryone: "Everyone",
    txtFieldHealthRisk: "Health Risk",
    txtImageSizeChallengeDesc: ".jpeg ; 1312 x 400",
    txtFieldStartDate: "Start Date",
    txtFieldEndDate: "End Date",

    txtFieldChallengeTemplateID: "Challenge Template ID",
    txtBtnAddNewTemplate: "ADD NEW TEMPLATE",
    txtAddNewTemplate: "Add New Template",
    txtChallengeTemplateDetail: "Challenge Template Detail",
    txtBtnUse: "USE",

    //competition
    txtFieldCompetitionBanner: "Competition Banner",
    txtFieldCompetitionTitle: "Competition Title",
    txtFieldCompetitionTitleInd: "Competition Title in Bahasa Indonesia",
    txtFieldShortDescription: "Short Description",
    txtFieldShortDescriptionInd: "Short Description in Bahasa Indonesia",
    txtAddNewCompetition: "Add New Competition",
    txtBtnAddNewCompetition: "ADD NEW COMPETITION",
    txtSearchCompetitionPlaceholder: "by ID, Title",
    txtFieldCompetitionID: "Competition ID",
    txtCompetitionDetail: "Competition Detail",
    txtTeam: "Team",
    txtAssignTeam: "Assign Team",
    txtChallengeList: "Challenge List",
    txtManuallyCreate: "Manually create team",
    txtAutomaticallyCreate: "Automatically create team",
    txtFieldTeamConfigration: "Team Configration",
    txtFieldNumberOfWinners: "Number Of Winners",
    txtFieldNumberOfTeams: "Number Of Teams",
    txtFieldTeamName: "Team Name",
    txtAddTeam: "+ Add Team",
    txtAddTeamTitle: "Add Team",
    txtFieldTeamNames: "Team Names",
    txtAssignTeamDescription: "Checks the names and then choose the destination team",
    txtAddToTeam: "Add To Team",
    txtFieldRewardDiamond: "Reward (diamonds)",

    txtMiniChallenge: "Mini Challenge",
    txtMiniChallengeList: "Mini Challenge List",
    txtAddMiniChallenge: "Add Mini Challenge",
    txtMiniChallengeDetail: "Mini Challenge Detail",
    txtFieldMiniChallengeName: "Mini Challenge Name",
    txtFieldCompletedDate: "Completed Date",
    txtLeaderboardHistory: "Leaderboard History",

    txtFieldNum: "Num",
    txtFieldDiamonds: "Diamonds",
    txtFieldMember: "Member",
    //dashboard
    txtUser: "User",
    txtCoins: "Coins",
    txtStatusIssued: "ISSUED",
    txtStatusRedeemed: "REDEEMED",
    txtOngoingChallenge: "Ongoing Challenge",
    txtFiveParameters: "FIVE PARAMETERS",
    txtNutritionalStatus: "Nutritional Status",
    txtBloodGlucose: "Blood Glucose",
    txtBloodPressure: "Blood Pressure",
    txtPhysicalInactivity: "Physical Inactivity",
    txtTotalCholesterol: "Total Cholesterol",
    txtNormalChallenges: "Normal Challenges",
    txtJoining: "JOINING",
    txtNonJoining: "NOT JOINING",
    txtWithDiamond: "WITH DIAMOND",
    txtWithoutDiamond: "WITHOUT DIAMOND",
    //reward
    txtFilterByCategory: "Filter By Category",
    txtFilterByCreator: "Filter By Creator",
    txtRewardSearchPlaceholder: "by ID, Name",
    txtFieldRewardsID: "Rewards ID",
    txtFieldRewardsName: "Rewards Name",
    txtFieldCreator: "Creator",
    txtFieldValidity: "Validity",
    txtStatusAvailable: "AVAILABLE",
    txtStatusUnavailable: "UNAVAILABLE",
    txtFieldCoins: "Coins",
    txtFieldImage: "Image",
    txtFieldRewardQuantity: "Reward Quantity",
    txtSectionRewardValidity: "CHOOSE THE REWARDS VALIDITY",
    txtSectionTermsAndConditions: "REWARDS TERM & CONDITIONS",
    txtAddMoreTerms: "+ Add More Term & Conditions",
    txtAvailable: "Available",
    txtUnavailable: "Unavailable",
    txtAddNewRewards: "Add New Rewards",
    txtBtnAddNewRewards: "ADD NEW REWARDS",
    txtRewardDetail: "Rewards Detail",
    txtTermsAndConditions: "Term & Conditions",

    //reward type
    txtBtnAddRewardType: "ADD NEW TYPE",
    txtAddNewRewardType: "Add New Reward Type",
    txtFieldRewardType: "Reward Type",
    txtFieldRewardTypeID: "Reward Type ID",
    txtRewardTypeDetail: "Reward Type Detail",


    //point hisotry

    txtFilterByUserName: "Filter By User Name",
    txtFilterByPayor: "Filter By Payor",
    txtFilterByType: "Filter By Type",
    txtStartDate: "Start Date",
    txtEndDate: "End Date",
    txtFieldPointHistoryID: "Point History ID",
    txtFieldDateAndTime: "Date & Time",
    txtFieldAmount: "Amount",
    txtFieldType: "Type",
    txtFieldTypeID: "Type ID",
    txtPointHistoryDetail: "Point History Detail",
    txtStatusIN: "IN",
    txtStatusOUT: "OUT",

    //package invoice
    txtPackageInvoice: "Package Invoice",
    txtFilterByPackage: "Filter by Package",
    txtPurchaseStartDate: "Purchase Start Date",
    txtPurchseEndDate: "Purchase End Date",
    txtFieldInvoiceID: "Invoice ID",
    txtFieldPayor: "Payor",
    txtFieldPurchaseDateTime: "Purchase Date & Time",
    txtPurchseStartDate: "Purchase Start Date",
    txtPurchaseEndDate: "Purchase End Date",
    txtFieldExpireDate: "Expire Date",
    txtFieldPrice: "Price",
    txtInvoice: "Invoice",
    txtFieldValidityDays: "Validity (days)",
    txtCreateOrder: "Create Order",
    txtFieldPackageInvoiceID: "Package Invoice ID",
    txtPackageInvoiceDetail: "Package Invoice Detail",
    txtBtnAddNewPackageInvoice: "ADD NEW PACKAGE INVOICE",
    txtAddNewPackageInvoice: "Add New Package Invoice",
    txtBtnExportToCSV: "EXPORT TO .CSV",
    txtChoosePayor: "Choose Payor",
    txtChoosePackage: "Choose Package",
    txtSelectPurchaseDateTime: "Select Date & Time",
    txtInputPrice: "Input Price",
    txtInputInvoiceID: "Input Invoice ID",

    txtBtnSeeAdminAccess: "SEE ADMIN ACCESS",
    txtStatusOnProgress: "ON PROGRESS",
    txtStatusPaid: "PAID",
    txtBtnCreateOrder: "CREATE ORDER",
    txtBtnOrder: "ORDER",
    txtBtnCancel: "CANCEL",

    //broadcast

    txtBtnAddNewBroadcast: "ADD NEW BROADCAST",
    txtBroadcastDetail: "Broadcast Detail",
    txtAddNewBroadcast: "Add New Broadcast",
    txtPostedStartDate: "Posted Start Date",
    txtPostedEndDate: "Posted End Date",
    txtFieldBroadcastID: "Broadcast ID",
    txtFieldBroadcastTitle: "Broadcast Title",
    txtFieldPostedDate: "Posted Date",

    //theme settings

    txtThemeColor: "Theme Color",
    txtThemePreview: "Theme Preview",
    txtButtonColor: "Button Color",

    //job level
    txtFieldJobLevelID: "Job ID",
    txtFieldJobLevelName: "Job Title",
    txtBtnAddNewJobLevel: "ADD NEW JOB",
    txtAddNewJobLevel: "Add New Job",
    txtJobDetail: "Job Detail",

    //department
    txtDepartment: "Department",
    txtFieldDepartmentID: "Department ID",
    txtFieldDepartmentName: "Department Name",
    txtBtnAddNewDepartment: "ADD NEW DEPARTMENT",
    txtAddNewDepartment: "Add New Department",
    txtDepartmentDetail: "Department Detail",



    //error handling messages
    txtErrNameRequired: "Please input name.",
    txtErrPeriod: "Please input period in days. ex: 365",
    txtErrPrice: "Please input price in Rp. ex: 500000",
    txtErrPhoneNumberInvalid: "Please input phone number. ex: +62 878 8898 8810",
    txtErrEmailInvalid: "Please input email. ex: company@mail.com",
    txtErrPasswordInvalid: "Please input password.",
    txtErrPayorPasswordInvalid: "Please input min 8 letter password.",
    txtErrOldPassword: "Please input old password.",
    txtErrNewPassword: "Please input new password.",
    txtErrConfirmPassword: "Please input confirm password.",
    txtErrBirthday: "Please input birthday.",
    txtErrDepartment: "Please select department",
    txtErrPayorSelect: "Please select payor.",
    txtErrPackageSelect: "Please select package.",
    txtErrTitleRequired: "Please input title.",
    txtErrNumberOfWinners: "Please input number of winners",
    txtErrNumberOfTeams: "Please input number of teams",
    txtErrImageRequired: "Please pick image.",
    txtErrChallengeCategory: "Please input challenge category.",
    txtErrTotalTarget: "Please input total target.",
    txtErrRewardPrize: "Please input reward prize.",
    txtErrRepeatFrequency: "Please choose repeat frequency",
    txtErrRepeatFor: "Please input number.",
    txtErrRepeatForCompetition: "End date should before competition end date.",
    txtErrStartDate: "Please input start date",
    txtErrStartDateCompetition: "Please input date after competition start date.",
    txtErrEndDate: "Please input correct date after start date",
    txtErrEndDateExtend: "You can only extend end date.",
    txtErrCoinInvalid: "Please input reward coin",
    txtErrQuantityInvalid: "Please input reward quantity",
    txtErrRewardCategory: "Please input reward category",
    txtErrPurchaseDateTime: "Please input purchase date & time",
    txtErrPackageInvoice: "Please input package invoice",
    txtErrSymptomRequired: "Please choose symptom",
    txtErrDate: "Please input date",
    txtErrCalories: "Please input calories",
    txtErrServingSize: "Please input serving size",
    txtErrGram: "Please input gram",
    txtErrCarb: "Please input carb",
    txtErrProtein: "Please input protein",
    txtErrFat: "Please input fat",
    txtErrCaloriesBurn: "Please input calories burn per minute.",
    txtErrMedicine: "Please select medicine.",
    txtErrMCUPayorInvalid: "Please select MCU Payor",
    txtErrMinimumAge: "Please input minimum age",
    txtErrMaximumAge: "Please input maximum age",
    txtErrMaximumAgeCompare: "Invalid maximum age (>= minimum age)",
    txtErrGender: "Please input gender",
    txtErrJob: "Please select job",
    txtErrHealthRisk: "Please select healthRisk",
    txtErrDescription: "Please input description",
    //success handling messages

    txtLoginSuccess: "Login successed.",
    txtLoginFailure: "Please check your email or password.",
    txtPackageCreateSuccess: "Package successfully created.",
    txtPackageUpdateSuccess: "Package successfully saved.",
    txtAccessUpdateSuccess: "Admin Accessibility successfully updated.",
    txtPayorCreateSuccess: "Payor successfully created",
    txtPayorUpdateSuccess: "Payor successfully saved",
    txtPackageDeleteSuccess: "Package successfully deleted",
    txtPayorDeleteSuccess: "Payor successfully deleted",
    txtChangePasswordSuccess: "Password successfully changed",

    txtEmployeeDeleteSuccess: "Employee successfully deleted",
    txtEmployeeCreateSuccess: "Employee successfully created",
    txtEmployeesCreateSuccess: "Employees successfully created",
    txtEmployeeUpdateSuccess: "Employee successfully saved",

    txtBannerDeleteSuccess: "Banner successfully deleted",
    txtBannerCreateSuccess: "Banner successfully created",
    txtBannerUpdateSuccess: "Banner successfully saved",

    txtJobDeleteSuccess: "Job Title successfully deleted",
    txtJobCreateSuccess: "Job Title successfully created",
    txtJobUpdateSuccess: "Job Title successfully saved",

    txtChallengeDeleteSuccess: "Challenge successfully deleted",
    txtChallengeCreateSuccess: "Challenge successfully created",
    txtChallengeUpdateSuccess: "Challenge successfully saved",

    txtCompetitionDeleteSuccess: "Competition successfully deleted",
    txtCompetitionCreateSuccess: "Competition successfully created",
    txtCompetitionUpdateSuccess: "Competition successfully saved",

    txtCompetitionChallengeDeleteSuccess: "Mini Challenge successfully deleted",
    txtCompetitionChallengeCreateSuccess: "Mini Challenge successfully created",
    txtCompetitionChallengeUpdateSuccess: "Mini Challenge successfully saved",

    txtTeamDeleteSuccess: "Competition Team successfully deleted",
    txtTeamCreateSuccess: "Competition Team successfully created",
    txtTeamUpdateSuccess: "Competition Team successfully saved",

    txtCompetitionTeamEmployeeDeleteSuccess: "Competition Team Employee successfully deleted",
    txtCompetitionTeamEmployeeCreateSuccess: "Competition Team Employee successfully created",
    txtCompetitionTeamEmployeeUpdateSuccess: "Competition Team Employee successfully saved",

    txtChallengeTemplateDeleteSuccess: "Challenge template successfully deleted",
    txtChallengeTemplateCreateSuccess: "Challenge template successfully created",
    txtChallengeTemplateUpdateSuccess: "Challenge template successfully saved",

    txtRewardTypeDeleteSuccess: "Reward Type successfully deleted",
    txtRewardTypeCreateSuccess: "Reward Type successfully created",
    txtRewardTypeUpdateSuccess: "Reward Type successfully saved",

    txtRewardDeleteSuccess: "Reward successfully deleted",
    txtRewardCreateSuccess: "Reward successfully created",
    txtRewardUpdateSuccess: "Reward successfully saved",

    txtBroadcastDeleteSuccess: "Broadcast successfully deleted",
    txtBroadcastCreateSuccess: "Broadcast successfully created",
    txtBroadcastUpdateSuccess: "Broadcast successfully saved",

    txtSymptomDeleteSuccess: "Symptom successfully deleted",
    txtSymptomCreateSuccess: "Symptom successfully created",
    txtSymptomUpdateSuccess: "Symptom successfully saved",

    txtSymptomRecordDeleteSuccess: "Symptom record successfully deleted",
    txtSymptomRecordCreateSuccess: "Symptom record successfully created",
    txtSymptomRecordUpdateSuccess: "Symptom record successfully saved",

    txtMealDeleteSuccess: "Food successfully deleted",
    txtMealCreateSuccess: "Food successfully created",
    txtMealUpdateSuccess: "Food successfully saved",

    txtMedicineDeleteSuccess: "Medicine successfully deleted",
    txtMedicineCreateSuccess: "Medicine successfully created",
    txtMedicineUpdateSuccess: "Medicine successfully saved",

    txtPrescriptionDeleteSuccess: "Prescription successfully deleted",
    txtPrescriptionCreateSuccess: "Prescription successfully created",
    txtPrescriptionUpdateSuccess: "Prescription successfully saved",

    txtExerciseDeleteSuccess: "Exercise successfully deleted",
    txtExerciseCreateSuccess: "Exercise successfully created",
    txtExerciseUpdateSuccess: "Exercise successfully saved",

    txtHealthRiskDeleteSuccess: "Health Risk successfully deleted",
    txtHealthRiskCreateSuccess: "Health Risk successfully created",
    txtHealthRiskUpdateSuccess: "Health Risk successfully saved",

    txtBloodGlucoseRecordDeleteSuccess: "Blood Glucose record successfully deleted",
    txtDietRecordDeleteSuccess: "Diet record successfully deleted",
    txtExerciseRecordDeleteSuccess: "Exercise record successfully deleted",

    txtWaterDeleteSuccess: "Water Record successfully deleted",
    txtVeggieDeleteSuccess: "Veggie Record successfully deleted",
    txtFruitDeleteSuccess: "Fruit Record successfully deleted",

    txtThemeSettingUpdateSuccess: "Theme setting successfully saved.",



    txtOrderCreateSuccess: "Package order successfully created",
    txtPackageInvoiceCreateSuccess: "Package invoice successfully created",


    txtOldPasswordNotCorrect: "Please check old password again.",

    txtUnexpectedError: "Unexpected error, Please contact with support team.",


    txtGood: "Good",
    txtBad: "Bad",
    txtMedium: "Medium",
};
export default stringsId;
